// 2-digit CIP prefix → subject area label (NCES Classification of Instructional Programs)
export const CIP_PREFIX_LABELS: Record<string, string> = {
  "01": "Agriculture",
  "03": "Natural Resources & Conservation",
  "04": "Architecture",
  "05": "Area & Cultural Studies",
  "09": "Communication & Journalism",
  "10": "Communications Technology",
  "11": "Computer & Information Sciences",
  "12": "Personal & Culinary Services",
  "13": "Education",
  "14": "Engineering",
  "15": "Engineering Technology",
  "16": "Foreign Languages & Linguistics",
  "19": "Family & Consumer Sciences",
  "22": "Legal Studies",
  "23": "English Language & Literature",
  "24": "Liberal Arts & Sciences",
  "25": "Library Science",
  "26": "Biological & Biomedical Sciences",
  "27": "Mathematics & Statistics",
  "29": "Military Technologies",
  "30": "Interdisciplinary Studies",
  "31": "Parks, Recreation & Fitness",
  "38": "Philosophy & Religious Studies",
  "39": "Theology & Religious Vocations",
  "40": "Physical Sciences",
  "41": "Science Technologies",
  "42": "Psychology",
  "43": "Homeland Security & Law Enforcement",
  "44": "Public Administration & Social Service",
  "45": "Social Sciences",
  "46": "Construction Trades",
  "47": "Mechanic & Repair Technology",
  "48": "Precision Production",
  "49": "Transportation & Materials Moving",
  "50": "Visual & Performing Arts",
  "51": "Health Professions",
  "52": "Business & Management",
  "54": "History",
  "60": "Residency Programs",
};
